### ISSUE TITLE
Example for using driller

### ISSUE THREAD

**Issue by ronakdborad** [shellphish/driller#12]
Can you please provide the example or script on how to use the driller for the binaries.

**Comment by zardus** [comment]
This is eternally on the TODO list, but we never have much time to devote to it. Driller is in very much an undocumented/unsupported (though, tested) state. If the impossible happens, and we have some time to spare, docs will happen, but until then it'd have to come from an external PR :-(

**Comment by ronakdborad** [comment]
Thanks for your response.

While running driller, it is stopping at '"looking for crashes". As below:
(driller) rborad@ESPRIMO-E920-Ubu:~/driller/driller-master$ python run.py /home/rborad/driller
INFO    | 2017-01-24 13:46:02,736 | driller | 1 binaries found
INFO    | 2017-01-24 13:46:02,736 | driller | 1 binaries found
INFO    | 2017-01-24 13:46:02,736 | driller | going to work on 1
INFO    | 2017-01-24 13:46:02,823 | driller | listening for crashes..

It is not moving further. Can you please what can be going wrong. Do I have to change anything in config file. 

### Redis Options
REDIS_HOST='127.0.0.1'
REDIS_PORT=6379
REDIS_DB=0

### Celery Options
BROKER_URL= 'redis://127.0.0.1:6379'

CELERY_ROUTES = None

### Environment Options

# directory contain driller-qemu versions, relative to the directoy node.py is invoked in
QEMU_DIR=None

# directory containing the binaries, used by the driller node to find binaries
BINARY_DIR=None
# directory containing the pcap corpus
PCAP_DIR=None

### Driller options
# how long to drill before giving up in seconds
DRILL_TIMEOUT=None

MEM_LIMIT=None

### Fuzzer options

# how often to check for crashes in seconds
CRASH_CHECK_INTERVAL=None

# how long to fuzz before giving up in seconds
FUZZ_TIMEOUT=None

# how long before we kill a dictionary creation process
DICTIONARY_TIMEOUT=None

# how many fuzzers should be spun up when a fuzzing job is received
FUZZER_INSTANCES=None

# where the fuzzer should place it's results on the filesystem
FUZZER_WORK_DIR=None

**Comment by salls** [comment]
I'm sorry, but we aren't going to be able to help with running Driller through celery and redis. Although we used that configuration when doing large scale tests, we aren't really familiar with setting those up. 

Driller should really have a 'simple' mode where it expects to just run in a single machine and just loops though the files in the afl queue to run driller tasks. Unfortunately, none of us have had time to write it. The test script https://github.com/shellphish/driller/blob/master/tests/test_driller.py shows an example of using driller with a single input. I personally would write a script that simply monitors afl and calls driller that way and injects the new testcases to afl.

**Comment by ronakdborad** [comment]
Thanks for your prompt responses.
I have modified the location of binary and the name of the binary in the test script test_driller.py
When I run it, it is stopping with error.

WARNING | 2017-01-30 12:48:40,161 | angr.path_history | "max_size" has been deprecated in Path.step(). Please use "size" instead.
WARNING | 2017-01-30 12:48:40,165 | angr.path_history | "max_size" has been deprecated in Path.step(). Please use "size" instead.
WARNING | 2017-01-30 12:48:40,166 | angr.path_history | "max_size" has been deprecated in Path.step(). Please use "size" instead.
WARNING | 2017-01-30 12:48:40,189 | angr.path_history | "max_size" has been deprecated in Path.step(). Please use "size" instead.
Traceback (most recent call last):
  File "test_driller.py", line 36, in <module>
    run_all()
  File "test_driller.py", line 33, in run_all
    all_functions[f]()
  File "test_driller.py", line 23, in test_drilling_cgc
    nose.tools.assert_equal(len(new_inputs), 7)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 13 != 7

Do you suggest any more changes to be made.

Thanks
- Ronak

**Comment by salls** [comment]
The test_driller script is just an example python script of how to find new paths with driller. Of course if you make it point at a different binary you will find a different number of new inputs. That's why you are getting the assertion error, since the test checks that 7 new inputs are found.

**Comment by ronakdborad** [comment]
So the new inputs which it gives, are they the crashing inputs or some initial testcases which it will use to detect the crash. If so how can I detect the crash.
When I print newinputs, it gives:
set([((4, 134513409, 134513424), '^\xfe^\xfe'), ((4, 134513230, 134513263), '\x00\x00\x00\x00'), ((4, 134513719L, 167772168), '^\xfe^\xfe'), ((4, 134513719L, 167772168), '\x01\xfe\xfe\xfe'), ((4, 134513373, 134513381), '\x01\xfe\xfe\xfe'), ((4, 134513719L, 167772168), '^\xfe\xa1\xfe'), ((4, 134513719L, 167772168), '\x00\x00\x00\x00')])

How can I interpret it.

**Comment by salls** [comment]
These are inputs which exercise different paths. The drilling step is only for finding inputs along new paths. You have to feed them back into AFL.

The redis code in Driller shows one way to combine the symbolic drilling with AFL.

If you haven't already read our NDSS paper on Driller you probably should.

**Comment by ronakdborad** [comment]
Oh, I got that. I  read the paper.
Can you help in determining the crashing input for binary say "CROMU_00001" using the scripts you provided. I want to test only single binary.

Thanks.

**Comment by salls** [comment]
I can't provide much help, we are students that have a ton of obligations and little time. You need to run AFL on the binary and then have a script that runs driller on the inputs that AFL finds.

**Comment by ronakdborad** [comment]
Ok. Thanks for your prompt responses.
