### ISSUE TITLE
self.trace "list index out of range" error

### ISSUE THREAD

**Issue by anon8675309** [shellphish/driller#22]
Here is a demo program so you can reproduce the results:
```
#!/usr/bin/env python
from driller.driller import Driller, l
from logging import DEBUG
from traceback import print_exc
l.setLevel(DEBUG)
target = "/home/grimm/targets/xz-5.2.3/src/xz/.libs/xz"
afl_input_filename = "a.xz"
with open(afl_input_filename, "rb") as f:
        afl_input = f.read()
d = Driller(target, afl_input)
try:
        solutions = d.drill()
except Exception as e:
        print_exc()
```

The base64 encoded contents of a.xz:
`/Td6WFoAAATm1rRGCgAhAeAAFwAHXQAg7gQKAAAAAADUnPZFGuu6oQABIxgcWkONH7bzfQEAAAA=`

The output of the demo listed above:
```
$ ./demo.py 
INFO    | 2017-03-16 19:28:11,350 | driller.Driller | [xz] drilling started on Thu Mar 16 19:28:11 2017
WARNING | 2017-03-16 19:28:11,350 | driller.Driller | Debug directory is not set. Will not log fuzzing bitmap.
Traceback (most recent call last):
  File "./demo.py", line 13, in <module>
    solutions = d.drill()
  File "/home/adam/.virtualenvs/driller/local/lib/python2.7/site-packages/driller/driller.py", line 110, in drill
    list(self._drill_input())
  File "/home/adam/.virtualenvs/driller/local/lib/python2.7/site-packages/driller/driller.py", line 136, in _drill_input
    t = tracer.Tracer(self.binary, self.input, hooks=self._hooks)
  File "/home/adam/.virtualenvs/driller/local/lib/python2.7/site-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 216, in __init__
    self.path_group = self._prepare_paths()
  File "/home/adam/.virtualenvs/driller/local/lib/python2.7/site-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 910, in _prepare_paths
    return self._linux_prepare_paths()
  File "/home/adam/.virtualenvs/driller/local/lib/python2.7/site-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 1099, in _linux_prepare_paths
    if pg.active[0].addr != self.trace[0]:
IndexError: list index out of range
```

The error is pretty straight forward: line 1099 accesses self.trace[0] without checking to see if there is at least one entry in self.trace (I checked, it is in fact self.trace, not pg.active).  I can patch that up and submit a pull request without any problem, but the real question is why there aren't any traces.  I have to suspect this is related to shared libraries not being loaded in xz due to them not being in standard paths.  To give a concrete example:

```
$ /home/grimm/targets/xz-5.2.3/src/xz/.libs/xz --help
/home/grimm/targets/xz-5.2.3/src/xz/.libs/xz: /lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by /home/grimm/targets/xz-5.2.3/src/xz/.libs/xz)
$ LD_PRELOAD="/home/grimm/targets/xz-5.2.3/src/liblzma/.libs/liblzma.so.5" /home/grimm/targets/xz-5.2.3/src/xz/.libs/xz --help
<output as expected>
```

To attempt to test if this was the problem, I hacked in `from os import environ`, set `environ['LD_PRELOAD'] = "/home/grimm/targets/xz-5.2.3/src/liblzma/.libs/liblzma.so.5"`, and added `env=environ` to the Popen calls in dynamic_trace().  This did not make a difference.

**If** the LD_PRELOAD issue is actually the cause of my problem, how can this be handled by Driller?  Anyone have any tips on where I should look to test/debug this faster?

**Comment by salls** [comment]
The Popen() calls are calling qemu which will not use LD_PRELOAD from the environment. I think you should try modifying the PATH environment variable. One way to debug this would be to just run qemu with the arguments provided in the Popen() command and make sure it works
