### ISSUE TITLE
How does afl-cgc deliver the input to the target program

### ISSUE THREAD

**Issue by xiaosatianyu** [shellphish/driller#29]
I find that the afl-cgc start the target-program in qemu mode using parameters such as "/shellphish-afl/bin/afl-cgc/tracers/i386/afl-qemu-trace  --  /binaries/tests/cgc/251abc02_01". But how does the afl-cgc give the input to the program? It does not add the location of the input file.
Thank you very much

**Comment by zardus** [comment]
Input is transmitted over stdin.
