### ISSUE TITLE
Unable to correct discrepancy between qemu and angr.

### ISSUE THREAD

**Issue by jakkdu** [shellphish/driller#31]
Hi, all.
I am testing the driller with CGC binaries that are compiled for x86.
Unfortunately, when I run the driller, I got an error "Unable to correct discrepancy between qemu and angr." 
I am not sure it is normal or I make some mistakes.

```python
import driller

d = driller.Driller("./CROMU_00005",
                        '6,0 5,21,6 1,55,2 6,42,6 2,56,4 4,50,6 0,54,5 6,61,5 1,46,6 7,89')
new_inputs = d.drill()
```

Here is the binary. I only changed syscall to equivalent x86 syscall. 
[CROMU_00005.zip](https://github.com/shellphish/driller/files/880533/CROMU_00005.zip)

Thanks.

**Comment by salls** [comment]
That is not normal and typically indicates an error. What happens if you try it with the origin CGC version of the binary?

**Comment by jakkdu** [comment]
Ok, it works if I use CGC binary. Thanks. 
You can close this issue if you want.

**Comment by salls** [comment]
It might mean we have some bug which is triggered by one of the linux syscalls. If you end up looking into it feel free to reopen this issue

**Comment by jakkdu** [comment]
I think it's fine for my testing.
But if I want a linux version, then I will open a new issue.
Thanks a lot.
