### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Tracer'

### ISSUE THREAD

**Issue by skybluehold** [shellphish/driller#36]
Hello,
I want this err fix..

I tried these command  
- [ sudo pip install tracer] 
- [ git clone https://github.com/angr/tracer && pip install tracer]
- [python test_driller]

How can i fix this err
 
```
Traceback (most recent call last):
  File "test_driller.py", line 34, in <module>
    run_all()
  File "test_driller.py", line 31, in run_all
    all_functions[f]()
  File "test_driller.py", line 19, in test_drilling_cgc
    new_inputs = d.drill()
  File "/root/.environments/angr/local/lib/python2.7/site-packages/driller/driller.py", line 113, in drill
    list(self._drill_input())
  File "/root/.environments/angr/local/lib/python2.7/site-packages/driller/driller.py", line 139, in _drill_input
    t = tracer.Tracer(self.binary, self.input, hooks=self._hooks, argv=self.argv)
**AttributeError: 'module' object has no attribute 'Tracer'**
```
![attributeerr](https://cloud.githubusercontent.com/assets/12509361/24753091/ad213a42-1b0b-11e7-9aa2-3ec385875414.png)

please help me

**Comment by rhelmot** [comment]
test_driller.py is not meant to be executed directly. It has no `#!/usr/bin/env python` line (called the "shebang line") at the top of the file, so when you execute it like that, it is interpreted as a bash script. You can tell this from the complaints that "import" is an invalid command.

You are supposed to run it as either `python test_driller.py` or `nosetests -v --nologcapture test_driller.py`

**Comment by skybluehold** [comment]
Thanks you!  
my python test code is
![image](https://cloud.githubusercontent.com/assets/12509361/24770641/a2685218-1b45-11e7-9caf-6a8440865c2c.png)

baby-re is executable bin.

and than i tried 
![image](https://cloud.githubusercontent.com/assets/12509361/24770821/3ddbe1c4-1b46-11e7-9b3d-3a109c073568.png)

**Comment by salls** [comment]
running `pip install tracer` does not install the tracer you cloned from github. try `pip install -e ./tracer`

**Comment by skybluehold** [comment]
Thanks you!

**Comment by carterMgj** [comment]
I meet the same problem when I use rex.  Have you ever solved your problem?

**Comment by KittyTechnoProgrammer** [comment]
I am having the same issue

**Comment by KittyTechnoProgrammer** [comment]
are you supposed to run this in a virtual environment

**Comment by twizmwazin** [comment]
You need to install `https://github.com/angr/tracer` in your virtualenv. Always use a virtualenv for angr, or really anything python.

**Comment by KittyTechnoProgrammer** [comment]
Thank you this is useful information. Thank you again for responding so quickly, and thank you for working on this project. New to the whole "fuzzing" thing. Used to doing it old school, but times are changing. I will try this solution.

I've installed the needed modules, and fix some SyntaxError: 'return' with argument inside generator
in the tracer module. This was the outcome. 

IOError: [Errno 2] No such file or directory: '/dev/shm/work/bof/sync/fuzzer-master/fuzz_bitmap'
('', None)

**Comment by KittyTechnoProgrammer** [comment]
This is in a virtualenv

**Comment by KittyTechnoProgrammer** [comment]
No getting an Error in driller

Traceback (most recent call last):
  File "/opt/fuzzer/fuzzer_venv/lib/python2.7/site-packages/driller/local_callback.py", line 122, in <module>
    for new_input in d.drill_generator():
  File "/opt/fuzzer/fuzzer_venv/local/lib/python2.7/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "/opt/fuzzer/fuzzer_venv/local/lib/python2.7/site-packages/driller/driller_main.py", line 111, in _drill_input
    r = tracer.qemu_runner.QEMURunner(self.binary, self.input, argv=self.argv)
  File "/opt/fuzzer/fuzzer_venv/src/tracer/tracer/qemu_runner.py", line 168, in __init__
    self._run()
  File "/opt/fuzzer/fuzzer_venv/src/tracer/tracer/qemu_runner.py", line 405, in _run
    self._load_core_values(core_target)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/fuzzer/fuzzer_venv/src/tracer/tracer/qemu_runner.py", line 252, in _tmpfile
    with contextlib.suppress(FileNotFoundError):
AttributeError: 'module' object has no attribute 'suppress'
('', None)

**Comment by KittyTechnoProgrammer** [comment]
Just to be clear we are supposed to use python2 or python3

**Comment by twizmwazin** [comment]
Python2 is dead, all of our work is either python3 or abandoned.
