### ISSUE TITLE
Dataset from Driller paper and apps that benefited from Driller

### ISSUE THREAD

**Issue by ekilmer** [shellphish/driller#37]
In the Driller paper, there are 13 applications that invoked and benefited from concolic execution. The public name for application with identifier `2b03cf01` is given as `NRFIN_00017` for the case study, but I'm wondering how to resolve the identifier to a public name for the other 12: `2bda8e01, 5d469c01, 576b9101, 5e453901, 77263701, 17422001, d113bd01, f8271b01, 16d55a01, 6787bf01, 76ddd501, f5adc401`. They look like CRC32 hashes, but what was being hashed? 

If you have the public name for each hash, that would be perfect. Even a binary sample might be sufficient so that I could run `strings` on it to find the public name.

I'd like to study more about these programs and how they would run on a native Linux environment with real `libc` functions. Any help would be appreciated! Thank you!

**Comment by salls** [comment]
Here's the name mapping I have.

[name_mapping.txt](https://github.com/shellphish/driller/files/972058/name_mapping.txt)

**Comment by ekilmer** [comment]
Thank you so much!
