### ISSUE TITLE
Simuvex Error

### ISSUE THREAD

**Issue by phros** [shellphish/driller#41]
Hey Guys,

I'm trying to get into driller. I wrote a simple program ([example.txt](https://github.com/shellphish/driller/files/1115414/example.txt)).

When running driller, I get the following output:
```
In [13]: d = driller.Driller("ex.run", "input", "\xff" * 65535)

In [14]: new = d.drill()
WARNING | 2017-06-30 16:06:40,422 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2017-06-30 16:06:41,279 | tracer.Tracer | Our base address doesn't match QEMU's. Changing ours to 0x4000000000
ERROR   | 2017-06-30 16:06:43,223 | simuvex.vex.irop | Unsupported operation: Iop_InterleaveHI32x4

In [15]: new
Out[15]: set()
```

Am I doing something wrong here? 

Cheers

**Comment by rhelmot** [comment]
You have done nothing wrong. simuvex just hasn't implemented the VEX operation Iop_InterleaveHI32x4, which is understandable given the [horrifying list of vex operations](https://github.com/angr/vex/blob/master/pub/libvex_ir.h). If you would like to implement this operation, you can do so in the file simuvex/engines/vex/irop.py. An example of a pull request implementing an IROp is https://github.com/angr/simuvex/pull/143

**Comment by phros** [comment]
Ok, Thanks for feedback! Will try my best!
