### ISSUE TITLE
How to stop the workers from celery?

### ISSUE THREAD

**Issue by xiaosatianyu** [shellphish/driller#42]
Hi:
I use  'celery -A tasks worker ---loglevel=info' to start wokers drilling into binaryies, but how can I stop these workers?
I just press "ctrl+c" in the terminal, which starts the tasks, but it does not work.
I run "pkill -9 -f 'celery' " to stop the process, but it would resume automately the next time I run  'celery -A tasks worker ---loglevel=info' without starting the driller.
Even I restart the computer, and I run  'celery -A tasks worker ---loglevel=info', without starting the driller, it would restart the workers automately.
How could I stop the workers?

**Comment by salls** [comment]
None of us have used celery in a long time, so we won't be able to help you here. 
One way to run driller on a single machine easily is here: https://github.com/shellphish/fuzzer/blob/master/shellphuzz

**Comment by salls** [comment]
Actually, see this comment by ekilmer. Seems like that is the correct way to run/stop stuff
https://github.com/shellphish/driller/issues/35#issuecomment-297569445
