### ISSUE TITLE
AttributeError: 'ArchAMD64' object has no attribute 'byte_width'

### ISSUE THREAD

**Issue by TN-root** [shellphish/driller#52]
when I want to run a driller's new_input like this 
![image](https://user-images.githubusercontent.com/30521851/33543048-6e908b98-d910-11e7-9951-fc4d1554bd95.png)
and it's says AttributeError:
![image](https://user-images.githubusercontent.com/30521851/33543519-48ab6a36-d912-11e7-862f-de3d06682d96.png)
what can I do for this problem?

**Comment by zardus** [comment]
It seems that your archinfo install is out of date.
