### ISSUE TITLE
driller.driller.DrillerEnvironmentError

### ISSUE THREAD

**Issue by Bennoli13** [shellphish/driller#57]
I tried to run driller starter code below with CADET_00001 file that i downloaded from https://github.com/angr/angr-doc/tree/master/examples/CADET_00001 (there are two types of binary files in here) but it cannot running well for those binary files with code error like picture below

import driller
d = driller.Driller("./CADET_00001",  # path to the target binary
                    "racecar", # initial testcase
                    "\xff" * 65535, # AFL bitmap with no discovered transitions
                   )
new_inputs = d.drill()

![screenshot from 2018-01-25 14-11-52](https://user-images.githubusercontent.com/34600849/35374024-1db8233a-01dc-11e8-872a-cb35f15bfb31.png)

Is there anyone can solve this problem?

**Comment by zardus** [comment]
Are you running in the `shellphish/mechaphish` docker container? If not, please try that.

**Comment by Bennoli13** [comment]
Hey @zardus , 

Do you have any documentation about shellphish/mechaphish? I just wanna know the details about it like what the container includes? I'm working about your Driller now and I wanna figure out what I can do to improve the Driller because it's interesting. Thanks

**Comment by zardus** [comment]
Check out how the container is made for that info: https://github.com/mechaphish/setup/blob/master//Dockerfile

**Comment by Bennoli13** [comment]
Hey @zardus ,

Sorry again, I already tried to follow all steps but still got problems. Here I attached my error. Do you have any idea how to solve it?
Btw there is no problem when I run angr, the error just appeared when I run Driller. Thanks before.
![2](https://user-images.githubusercontent.com/34600849/35630152-905333ae-06db-11e8-9c30-e149a80bf262.PNG)

**Comment by zardus** [comment]
As it says in the error message, the binary should be executable...

**Comment by Bennoli13** [comment]
Dear @zardus ,

Thanks Yan, I run "chmod +x CADET_00001" first to make it executable (and it solved the first error) but unfortunately eventhough I run it for executable binary it still got error for the module in driller_main.py
Here I attached my error again. Have any idea to solve it? 
![screenshot from 2018-02-01 09-50-13](https://user-images.githubusercontent.com/34600849/35657080-9736dfea-0735-11e8-8990-ca7c93c113c9.png)

**Comment by zardus** [comment]
That's weird. Does the shellphuzz script work?

**Comment by Bennoli13** [comment]
Dear @zardus ,

Oh the problem comes from its fuzzer. I think it didn't run correctly. I tried run shellphuzz but it didn't work. Here I attached the error. I used user angr and root but both didn't work. Btw I already tried to re-pull but still I can't figure out how to solve it. Do u have any idea? Did I miss something when configure it?
here when I run it with user angr
![1](https://user-images.githubusercontent.com/34600849/35680867-83beff18-0796-11e8-8c36-39b33aa97793.PNG)
here when I run with user root
![2](https://user-images.githubusercontent.com/34600849/35680924-b7f8eb54-0796-11e8-825b-e2636f8bdc20.PNG)

Btw from shellphuzz documentation https://github.com/shellphish/fuzzer I tried to run sudo apt-get build-dep qemu but it failed like this 
![3](https://user-images.githubusercontent.com/34600849/35681044-1f6cd8d6-0797-11e8-81cc-0f39da6dd6a2.PNG)

Do you think the error also related with this?

**Comment by zardus** [comment]
You didn't specify the binary when you executed shellphuzz....
