### ISSUE TITLE
How to make Driller works on x86 binary file?

### ISSUE THREAD

**Issue by Bennoli13** [shellphish/driller#58]
Hi guys...,

I'm just wondering because I think Driller should be a powerfull tools. Angr can works on binary X86 and AFL too but I found out Driller cannot do that. I tried to see into the Driller's code but cannot find out. Just found that there is a piece of code to make sure the binary input is CGC. I also read the issue related about it but the explanation that I got just because the environment didn't support it. My question are (1) Is the ANGR's environment didn't support to analyze x86? Is it because ANGR that used in DRILLER already have the library about CGC? (2) Is it possible to try make it works for x86? (3) Do u have any suggestion what I should learn about and focus on if I wanna try to run Driller works on x86? Thanks before. Sorry if my question is too shallow, I'm just starting to learnt Driller.

**Comment by zardus** [comment]
I think you know this, based on your issue text, but just to clear things up: x86 is an architecture, and CGC is an OS (that normally happens to run on the x86 architecture, btw). angr supports analyzing x86 code, and angr has full support for the CGC system calls. However, angr's support for real operating system environments (such as Linux and Windows system calls) is lacking (though slowly improving).

You can see angr's Linux environment implementation here, for example: https://github.com/angr/angr/tree/master/angr/procedures/linux_kernel. There are *many* missing system calls there, and many that are there are just stubs. Most of the work to get Driller working on Linux binaries is expanding the list of system calls that are well supported. Part of this also involves expanding angr's ability to reason about the underlying concepts, like a filesystem (currently being worked on by @rhelmot, for example), processes, etc. There are a lot of fundamental, unsolved problems there to do it completely.

My advice is to take a *simple* binary that you want to use Driller on, see where it fails (i.e., diverges from the qemu execution trace), figure out why that is, fix that, and repeat the process until it works.

**Comment by Bennoli13** [comment]
Oh sorry I forgot to mention it, I mean X86 on Linux. Btw, thanks a lot @zardus .
