### ISSUE TITLE
Driller Interesting Branch 

### ISSUE THREAD

**Issue by bennoli** [shellphish/driller#63]
Hey guys, I hope you can help me to fully understand this tools.

I'm using Driller now but I still cannot figure it out, technically, how Driller choose a certain path to run Angr on it. Is it just based on hit counts? Or do you have any way to select interesting branches? (Interesting means that branch which has unexplored arm)

**Comment by rhelmot** [comment]
It's based on AFL's metric of "interesting branches", and is invoked whenever AFL reports that it's stuck. Look at the [shellphuzz script](https://github.com/shellphish/fuzzer/blob/master/shellphuzz) to see the top-level view of how driller is integrated into AFL.

**Comment by bennoli** [comment]
Dear @rhelmot ,

Thanks for your comments. For the last I just want to make sure, as I know from your code on shellphuzz, the interesting branch and also interesting input, those are decided by the AFL. Am I right? 
Do you guys use original AFL or you did some modification on AFL about this part? (to select the branch and the interesting input). Thanks

**Comment by rhelmot** [comment]
Yes, it's all AFL. no modifications. Our mechanism for building AFL can be found in the [shellphish-afl repository](https://github.com/shellphish/shellphish-afl).
