### ISSUE TITLE
Broken link to paper in README

### ISSUE THREAD

**Issue by pbst** [shellphish/driller#65]
Following the [current link](https://www.internetsociety.org/sites/default/files/blogs-media/driller-augmenting-fuzzing-through-selective-symbolic-execution.pdf) results in a 404.

A search engine found [this mirror](https://cancer.shtech.org/wiki/uploads/2016---NDSS---driller-augmenting-fuzzing-through-selective-symbolic-execution.pdf).

**Comment by rhelmot** [comment]
I found an improved mirror and used that. Thanks! :)
