### ISSUE TITLE
First Found?

### ISSUE THREAD

**Issue by Owlz** [shellphish/driller#9]
As you get deeper into drilling into the binaries, Driller itself takes quite a while to come back. Since this would be a bit of an architecture change, what are your thoughts on an option in driller that allows an "early exit".

Basically, be able to return on the first new path found. The hope would be you would then toss that new path into your fuzzer and let it hopefully find you more instead of waiting around for the entire code path to be drilled.

**Comment by zardus** [comment]
Driller exposes a testcase generator that gives you back testcases as it find them. That's how we use it in the Mechanical Phish (see: https://github.com/mechaphish/worker/blob/master/worker/workers/driller.py#L48). It might be worth exposing this more readily outside of the mechaphish context, though.

**Comment by Owlz** [comment]
Ahh. Nice. Yeah, `next(drill.drill_generator())` was what i was looking for. Thanks!
